### ISSUE TITLE
Document PHP version requirements

### ISSUE THREAD

**Issue by bvibber** [cedaro/shiny-code#2]
I tried to install the 0.1.0 release on an old Debian box that has PHP 5.6.36, which can't parse the return type declarations in Plugin.php.

I can update my box to PHP 7, but this'd be a good thing to explicitly document in the readme.

And thanks -- the project looks great; it sounds like it'll do what I want and I'm excited to try it! :)

**Comment by bvibber** [comment]
(I can confirm that it's working great after updating to PHP 7.0 on Debian stretch.)

**Comment by bradyvercher** [comment]
That could definitely be documented better. There is a header in the main plugin file, but I don't think WP core has fully implemented support for that yet. I'll add a note to the readme.

Glad to hear you were able to get it working after upgrading!

**Comment by afragen** [comment]
Hopefully 4.9.9 will fix this.

**Comment by afragen** [comment]
But that would only pull from readme.txt for plugins in dot org.

**Comment by bradyvercher** [comment]
@afragen I haven't been following the discussion regarding the `Requires PHP` header. Will it really only work in the readme? I was thinking core would use it during activation to prevent incompatible plugins from being activated.

**Comment by afragen** [comment]
@bradyvercher unfortunately it will only work from the readme.txt. The official header is `Requires PHP:` It is for a minimum version requirement and should be a valid semver style version.

GitHub Updater does check a similar `Requires PHP:` header in the main plugin file, but only for updates, not for installs.

For reference:
https://core.trac.wordpress.org/ticket/43986
https://core.trac.wordpress.org/ticket/43987
https://core.trac.wordpress.org/ticket/44350
https://core.trac.wordpress.org/ticket/44458

These should all be part of the Health Check stuff for WP 4.9.9

**Comment by bradyvercher** [comment]
Thanks for that info, @afragen! At least the plugin header is useful for GitHub Updater 😄
