### ISSUE TITLE
Fatal error: Uncaught Error: When activating Plugin

### ISSUE THREAD

**Issue by T1mNetherlands** [cedaro/shiny-code#5]
Hi, a newbie here, so i hope this is the right place to ask this question:
I have an issue with Activating the Shiny Code plugin.

Fatal error: Uncaught Error: Class 'Cedaro\WP\BlockType\Code\Plugin' not found in /www/wp-content/plugins/shiny-code-master/shiny-code.php:51 Stack trace: #0 /www/wp-admin/includes/plugin.php(1909): include() #1 /www/wp-admin/plugins.php(172): plugin_sandbox_scrape('shiny-code-mast...') #2 {main} thrown in /www/wp-content/plugins/shiny-code-master/shiny-code.php on line 51

Latest PHP, WP 5.0.1 Not sure what I'm doing wrong.

**Comment by bradyvercher** [comment]
Did you follow the [installation instructions](https://github.com/cedaro/shiny-code#installation)? It sounds like you may have downloaded the source, which requires going through a series of build steps and is really only necessary if you're planning on modifying the source.

Otherwise, you should download the release asset named `shiny-code-0.1.0.zip`, which can be installed without going through any extra steps.

**Comment by T1mNetherlands** [comment]
Im so sorry. I didn't follow the right instructions. I can delete this post? ;)

**Comment by bradyvercher** [comment]
No problem. Glad to hear it was an easy fix! I'll be pushing out an update in a bit to take care of some issues with WordPress 5.0, so keep an eye out for that.

**Comment by afragen** [comment]
@bradyvercher it might be easier to use the conditional at 
https://github.com/cedaro/shiny-code/blob/3bba8bb6d6d8c3180c9dc81f244ec35888500036/shiny-code.php#L46-L48
To be something like the following and reverse the logic.

```php
if ( ! file_exists( __DIR__ . '/vendor/autoload.php' ) ) {
	return;
}
require __DIR__ . '/vendor/autoload.php';
```

This way if someone installs the plugin incorrectly nothing will happen.

**Comment by bradyvercher** [comment]
@afragen That would work in this case, but the autoloader won't exist in the plugin directory for people that manage their entire site with Composer. I suppose I could always check to see if an autoloaded class doesn't exist and display an more user-friendly admin notice, though. Thanks for the suggestion!

**Comment by afragen** [comment]
It was a thought. I’m not sure what does and doesn’t show up if the entire site is managed via composer. At some point there’s simply a diminished return on trying to find an elegant solution instead of simply saying, “please following the installation instructions.” 😉
